name: HanLien
favicon: null
layout_spectrum: 0.48909175815060735
typography_spectrum: 0.8312563779763877
title: 'Han Lien | Tech Savvy Marketing & Information Systems Professional'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-37370380-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000e26'
    - '#ffffff'
    - '#c7cacf'
    - '#787f8c'
    - '#283347'
  brandStrength: 0.5
  lightness: 0.15703976922668517
  saturation: 0.8952596036251634
  rhythmicContrast: 0.23776976740919054
purpose: []
